---
#Set Proxmox Variables
- name: Set Variables
  any_errors_fatal: true
  gather_facts: false
  hosts: proxmox
  tasks:
    - include_tasks: ../tasks/set_proxmox_vars.yaml

#Boot up machines
- name: Start VMs
  any_errors_fatal: true
  gather_facts: false
  hosts: proxmox
  tasks:
    - include_tasks: ../tasks/startup_vm.yaml

#Update Packages
- name: Update VMs
  any_errors_fatal: true
  become: true
  become_user: root
  gather_facts: false
  hosts: VMnotele
  tasks:
    - include_tasks: ../tasks/apt_upgrade.yaml

# #Shutdown machines
# - name: Stop VMs
  # any_errors_fatal: true
  # gather_facts: false
  # hosts: proxmox
  # tasks:
    # - include_tasks: ../tasks/shutdown_vm.yaml

#Shutdown machines
- name: Shutdown VMs
  any_errors_fatal: true
  become: true
  become_user: root
  gather_facts: false
  hosts: VMnotele:!VMalwayson
  tasks:
    - include_tasks: ../tasks/shutdown_ans_vm.yaml