---
### Parameters
# swap_configure: true # or false
# swap_enable: true # or false
# swap_file_path: /swapfile
# swap_file_size_mb: 1536000
# swappiness: 1

    - name: Configure swap
      when: swap_configure | bool
      block:

        - name: Check if swap file exists
          stat:
            path: "{{swap_file_path}}"
            get_checksum: false
            get_md5: false
          register: swap_file_check
          changed_when: false

        - name: Set variable for existing swap file size
          set_fact:
            swap_file_existing_size_mb: "{{ (swap_file_check.stat.size / 1024 / 1024) | int }}"
          when: swap_file_check.stat.exists

        - name: Check if swap is on
          shell: swapon --show | grep {{swap_file_path}}
          register: swap_is_enabled
          changed_when: false
          failed_when: false

        - name: Disable swap
          command: swapoff {{swap_file_path}}
          register: swap_disabled
          when: >
            swap_file_check.stat.exists
            and 'rc' in swap_is_enabled and swap_is_enabled.rc == 0
            and (not swap_enable or (swap_enable and swap_file_existing_size_mb != swap_file_size_mb))

        - name: Delete the swap file
          file:
            path: "{{swap_file_path}}"
            state: absent
          when: not swap_enable

        - name: Remove swap entry from fstab
          mount:
            name: none
            src: "{{swap_file_path}}"
            fstype: swap
            opts: sw
            passno: '0'
            dump: '0'
            state: present
          when: not swap_enable

        - name: Configure swap
          when: swap_enable | bool
          block:

            - name: Create or change the size of swap file
              command: dd if=/dev/zero of={{swap_file_path}} count={{swap_file_size_mb}} bs=1MiB
              register: swap_file_created
              when: >
                not swap_file_check.stat.exists
                or swap_file_existing_size_mb != swap_file_size_mb

            - name: Change swap file permissions
              file:
                path: "{{swap_file_path}}"
                mode: 0600

            - name: Check if swap is formatted
              shell: file {{swap_file_path}} | grep 'swap file'
              register: swap_file_is_formatted
              changed_when: false
              failed_when: false

            - name: Format swap file if it's not formatted
              command: mkswap {{swap_file_path}}
              when: >
                ('rc' in swap_file_is_formatted and swap_file_is_formatted.rc > 0)
                or swap_file_created.changed

            - name: Add swap entry to fstab
              mount:
                name: none
                src: "{{swap_file_path}}"
                fstype: swap
                opts: sw
                passno: '0'
                dump: '0'
                state: present

            - name: Turn on swap
              shell: swapon -a
              # if swap was disabled from the start
              # or has been disabled to change its params
              when: >
                ('rc' in swap_is_enabled and swap_is_enabled.rc != 0)
                or swap_disabled.changed

            - name: Configure swappiness
              sysctl:
                name: vm.swappiness
                value: "{{ swappiness|string }}"
                state: present