---
    - name: Trim all filesystems
      command:
        argv:
          - fstrim -av

    - name: "Start & Enable fstrim Timer"
      service:
        name: "fstrim.timer"
        state: "started"
        enabled: true