---
    - name: Install a list of packages
      apt:
        pkg:
          - cloud-init
          - qemu-guest-agent
          - sudo
          - git
          - curl
          - mlocate
          - resolvconf
          - htop
          - net-tools
          - dnsutils
        state: present
        force_apt_get: "yes"
        update_cache: "yes"
        install_recommends: "no"