---
    - name: Remove /etc/machine-id and /var/lib/dbus/machine-id
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/machine-id
        - /var/lib/dbus/machine-id

    - name: Generate new machine-id
      command: systemd-machine-id-setup
# sudo rm -rf /etc/machine-id /var/lib/dbus/machine-id && sudo systemd-machine-id-setup && sudo reboot now