---
    - name: Proxmox stop VMs
      community.general.proxmox_kvm:
        api_user: "{{ prox_user }}"
        api_password: "{{ prox_pass }}"
        api_host: "127.0.0.1"
        node: "proxmox"
        vmid: "{{ item }}"
        state: "stopped"
      loop:
        - 1101
        - 1106
        - 1254
        - 2206
        - 9000
        - 9001
        - 9002