---
    - name: Proxmox start VMs
      community.general.proxmox_kvm:
        api_user: "{{ prox_user }}"
        api_token_id: "{{ prox_token_id }}"
        api_token_secret: "{{ prox_token_secret }}"
        api_host: "127.0.0.1"
        node: "proxmox"
        vmid: "{{ item }}"
        state: "started"
      loop:
        - 1100
        # - 1103 # Used for Bastion
        - 1104
        - 1105
        - 1110
        - 1254
        # - 9000
        - 9001
        # - 9002
        - 9005
        - 9006
