---
    - name: Proxmox start VMs
      community.general.proxmox_kvm:
        api_user: "{{ prox_user }}"
        api_token_id: "{{ prox_token_id }}"
        api_token_secret: "{{ prox_token_secret }}"
        api_host: "192.168.0.251"
        node: "proxmox"
        name: "{{ inventory_hostname }}"
        state: "started"
      delegate_to: localhost
