---
    - name: Proxmox start Teleport
      community.general.proxmox_kvm:
        api_user: "{{ prox_user }}"
        api_token_id: "{{ prox_token_id }}"
        api_token_secret: "{{ prox_token_secret }}"
        api_host: "127.0.0.1"
        node: "proxmox"
        vmid: "{{ item }}"
        state: "started"
      loop:
        - 1107
        - 1108
        - 1109
        # - 1110
        # - 1111
        # - 1112
        # - 1113