---
# Add SSH Keys for Proxmox
- name: Add SSH Keys for Proxmox
  any_errors_fatal: true
  gather_facts: false
  connection: local
  hosts: proxmox
  tasks:
    - include_tasks: ../tasks/eval_ssh_agent.yaml

# Add SSH keys for root
- name: Add SSH Keys for VMs
  any_errors_fatal: true
  become: true
  become_user: root
  connection: local
  gather_facts: false
  hosts: teleport
  tasks:
    - include_tasks: ../tasks/eval_ssh_agent.yaml

# Main tasks
- name: Update VMs
  any_errors_fatal: true
  gather_facts: false
  become: true
  hosts: teleport
  tasks:
    - name: Set Proxmox Variables
      include_tasks: ../tasks/set_proxmox_vars.yaml
    - name: Startup VMs
      include_tasks: ../tasks/startup_vm.yaml
    - name: Update Packages
      include_tasks: ../tasks/apt_upgrade.yaml
    - name: Run FSTrim
      include_tasks: ../tasks/run_fstrim.yaml
    - name: Shutdown VMs
      include_tasks: ../tasks/shutdown_ans_vm.yaml

# Remove SSH Keys for Proxmox
- name: Remove SSH Keys for Proxmox
  any_errors_fatal: true
  gather_facts: false
  hosts: proxmox
  tasks:
    - include_tasks: ../tasks/remove_ssh_keys.yaml

# Remove SSH keys for root
- name: Remove SSH Keys for VMs
  any_errors_fatal: true
  become: true
  become_user: root
  connection: local
  gather_facts: false
  hosts: teleport
  tasks:
    - include_tasks: ../tasks/remove_ssh_keys.yaml
