---
#Add SSH Keys for local
- name: Add SSH Keys for local
  any_errors_fatal: true
  gather_facts: false
  connection: local
  hosts: proxmox
  tasks:
    - include_tasks: ../tasks/eval_ssh_agent.yaml

#Add SSH keys for root
- name: Add SSH Keys for root
  any_errors_fatal: true
  become: true
  become_user: root
  connection: local
  serial: 20
  gather_facts: false
  hosts: VMnotele
  tasks:
    - include_tasks: ../tasks/eval_ssh_agent.yaml

#Set Proxmox Variables
- name: Set Variables
  any_errors_fatal: true
  gather_facts: false
  hosts: proxmox
  tasks:
    - include_tasks: ../tasks/set_proxmox_vars.yaml

#Boot up machines
- name: Start VMs
  any_errors_fatal: true
  gather_facts: false
  hosts: proxmox
  tasks:
    - include_tasks: ../tasks/startup_vm.yaml

#Update Packages
- name: Update VMs
  any_errors_fatal: true
  become: true
  serial: 20
  gather_facts: false
  hosts: VMnotele
  tasks:
    - include_tasks: ../tasks/apt_upgrade.yaml

#Shutdown machines
- name: Shutdown VMs
  any_errors_fatal: true
  become: true
  become_user: root
  serial: 20
  gather_facts: false
  hosts: VMnotele:!VMalwayson
  tasks:
    - include_tasks: ../tasks/shutdown_ans_vm.yaml

#Remove SSH Keys for local
- name: Remove SSH Keys for local
  any_errors_fatal: true
  gather_facts: false
  hosts: proxmox
  tasks:
    - include_tasks: ../tasks/remove_ssh_keys.yaml

#Remove SSH keys for root
- name: Remove SSH Keys for root
  any_errors_fatal: true
  become: true
  become_user: root
  connection: local
  serial: 20
  gather_facts: false
  hosts: VMnotele
  tasks:
    - include_tasks: ../tasks/remove_ssh_keys.yaml
