---
- name: Install docker
  hosts: docker
  become: true
  any_errors_fatal: true
  tasks:
    - include_tasks: ../tasks/docker_install.yaml

- name: Run container
  hosts: docker
  become: true
  any_errors_fatal: true
  gather_facts: false
  vars:
    container_count: 1
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1
  tasks:
    - include_tasks: ../tasks/docker_create_container.yaml