---
#Set Proxmox Variables
- name: Add repo
  any_errors_fatal: true
  become: true
  become_user: root
  serial: 10
  gather_facts: false
  hosts: teleport
  tasks:
    - include_tasks: ../tasks/add_repo_teleport.yaml