---

postgresql_cluster_reset      : true
postgresql_data_directory     : "/mnt/db/postgresql/{{postgresql_version}}/{{postgresql_cluster_name}}"
postgresql_listen_addresses   : ["0.0.0.0"]
postgresql_pg_hba_trust_hosts : ["0.0.0.0/0"]

postgresql_databases          : [
                                  {name: "products"},
                                  {name: "partners"}
                                ]

postgresql_users              : [
                                  {name: "jane", pass: "{{ postgresql_users_jane }}"},
                                  {name: "joe", pass: "{{ postgresql_users_joe }}"}
                                ]

postgresql_user_privileges    : [
                                  {name: "jane", db: "products"},
                                  {name: "joe", db: "partners"}
                                ]